### ISSUE TITLE
types not exported as documentation suggests

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#1]
this is what's exported, you'll notice statics like `AxiosLogger.using` are not exported (not really sure why they aren't emitted). also the docs have you package name wrong.

```ts
import { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import { LogFn } from "pino";
interface Headers {
    [key: string]: string | object;
}
interface HeaderRecord {
    key: string;
    value: string | object;
}
export declare const indent = "  ";
declare type ErrorSource = 'Request' | 'Response';
export declare class AxiosLogger {
    protected ignoreHeaderKeys: string[];
    protected logInfo: LogFn;
    protected logError: LogFn;
    constructor(infoFn?: LogFn, errorFn?: LogFn);
    logRequest(request: AxiosRequestConfig): void;
    logResponse(resp: AxiosResponse): void;
    logErrorDetails(err: any): void;
    protected parseError(error: AxiosError, errorSource: ErrorSource): string;
    protected parseRequest(request: AxiosRequestConfig): string;
    protected parseResponse(resp: AxiosResponse): string;
    protected startingLine(name: any): string;
    protected endingLine(): string;
    protected title(detailName: string): string;
    protected newLine(): string;
    protected prettyFormatBody(body: string | object): string;
    protected parseHeaders(headers: Headers): string;
    protected transformHeadersToStringArr(headers: Headers): string[];
    protected prettyHeaderEntry(headerEntry: HeaderRecord, isFirstElement: boolean, isLastElement: boolean): string;
}
export {};
```

**Comment by azakordonets** [comment]
Hmmm, interesting. Sorry about that - i'm starting with Typescript recently. Will try to fix that soon.

**Comment by xenoterracide** [comment]
yeah, I'll be honest, I don't get why these aren't available on the class either, seems like they should be...

**Comment by azakordonets** [comment]
I had a problem with publishing new versions of the library to npm from Github. Now it should be fixed in `v0.1.3` - can you please give it a try ? @xenoterracide

**Comment by xenoterracide** [comment]
using is now exported, I notice a lot of the same protected stuff isn't but maybe that's not supposed to be a part of your published api. What was the issue? out of curiousity.

**Comment by azakordonets** [comment]
@xenoterracide i have 2fa on this account and i need to setup properly tokens in Github in order to public from CI. Will do that later. For now publishing from my local machine. And the problem you had was because the first version that was published on npm was using an old code. When i refactored the library, publishing was taking too long on Github and i forgot to check it's state :) It appeared to be broken and therefore my changes were not properly published to npm.
