### ISSUE TITLE
formatting and filters

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#3]
an 8 space tab seems pretty extreme, it'd be nice to be able to configure this somehow. Of course this may be an assumption and the server is actually returning this... if it is then maybe it'd be nice to be able to provide a custom formatter to the Body.

also it would be good to be able to apply sanitization before writing logs to Body and Headers, for example it'd be a good idea to sanitize the sensitive parts of the Authorization header.

**Comment by azakordonets** [comment]
Yeah, nice idea. I will take a look at it. Will provide a config for tabs + i can also add config param for a list of fields that should be sanitized.

**Comment by xenoterracide** [comment]
further thoughts... I'm not certain that things should just be stripped so much as obscured... or maybe templated, e.g. like I mentioned in the other ticket, https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#using-response-handler-scripts. You don't want to think the Authorization header is missing, but you do want the secure content portion to not be logged. Although to be fair... I'm not turning this logger on in production anyways.

Another thing maybe, allow setting say..

```ts
{
    headers: true
    body: true
}
```
where setting to false would disable logging of the headers or body. This would be useful for just noise reasons.

**Comment by azakordonets** [comment]
Good idea. I will take it into account, thanks!

**Comment by azakordonets** [comment]
@xenoterracide i have release it in v.0.1.5 . More details you can find in documentation or in this PR - https://github.com/new10com/axios-logger/pull/9 . Let me know what you think when you have a moment. 
Thanks.

**Comment by xenoterracide** [comment]
I've only tried obfuscation, but that looks good to me, indentation seems to be better out of the box too. In general the config looks fine. I'll let you close if you want.

**Comment by azakordonets** [comment]
Thanks, closing for now. If you have any other suggestions - let's have it in a separate ticket :)
