### ISSUE TITLE
obfuscating parts of body payload

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#30]
ok, plugins is my proposed solution, because my specific problem is urlencoded which seems reasonable, but if the problem is in json, or even worse xml, then it would get ridiculous and seems. like not your problem.

```
[back-end]   Method: @POST
[back-end]   Headers:
[back-end]   ├ accept: "application/json"
[back-end]   ├ content-type: "application/x-www-form-urlencoded"
[back-end]   └ Accept: "application/json, text/plain, */*"
[back-end]   Body:
[back-end]   client_id=someid&client_secret=somesecret&grant_type=client_credentials
```
obviously I'd like to obfuscate someid and somesecret, tried adding those as keys but it didn't work

the response returns

```
[back-end]   Method: @POST
[back-end]   Status: 200  OK
[back-end]   Headers
[back-end]   ┌ server: "mithril"
[back-end]   ├ date: "Thu, 31 Mar 2022 14:53:19 GMT"
[back-end]   ├ content-type: "application/json"
[back-end]   ├ transfer-encoding: "chunked"
[back-end]   ├ connection: "close"
[back-end]   ├ cache-control: "no-store"
[back-end]   ├ pragma: "no-cache"
[back-end]   └ strict-transport-security: "max-age=31536000; includeSubDomains"
[back-end]   Body:
[back-end]   {
[back-end]      "issued_at": 1648738399,
[back-end]      "token_type": "Bearer",
[back-end]      "access_token": "bigtoken",
[back-end]      "expires_in": 1296000
[back-end]   }
```

obviously I'd want to obfuscate bigtoken too, maybe something like this this could work

```ts
const axiosLogger = AxiosLogger.default({
  obfuscation: {
    obfuscate: true,
    body: {
       sanitizers: {
          'application/x-www-form-urlencoded': AxiosLoggerSanitizer.formEncoded('client_id','client_secret')
           'application/json': body => JsonPath...here
       },
    }
  },
})
```

**Comment by xenoterracide** [comment]
side comment doesn't look like an `authorization:` header is obscured by default, is your existing code case sensitive?

**Comment by azakordonets** [comment]
Could be. Will need to double check that

**Comment by azakordonets** [comment]
@xenoterracide  Regarding case sensitivity. We are using [redact-object](https://www.npmjs.com/package/redact-object) library for obfuscation and therefore we don't control case sensitivity in this case. As for the custom obfuscation - what do you think about adding a possibility to pass a custom function that will do the obfuscation you want in regards to the request/response body or headers ? This way I don't have to build much logic, but rather just apply whatever function you would like to pass ?

**Comment by azakordonets** [comment]
Actually @xenoterracide I have release a new `0.2.7` version where you can find this [changes](https://github.com/new10com/axios-logger/commit/3f073519c2a0fda15f6eec29d7398072d6c3d982) I think that it could be exactly what I meant. You can pass a custom function as `replaceVal` in the obfuscation config and there you can check for key and if key if what you need - you can have your custom obfuscation done there. 

Let me know what you think about this

**Comment by azakordonets** [comment]
@xenoterracide would this implementation work for you ?

**Comment by xenoterracide** [comment]
I'll be looking into this implementation soon... As I'm supposed to be fixing some stuff like this soon. It's currently in my this sprint list

**Comment by xenoterracide** [comment]
yeah, seeing if this works for #32 but I don't see how, I did add `client_secret` as a key

```ts
  obfuscation: {
    obfuscate: true,
    redactableKeys: ['Authorization', 'username', 'password', 'client_secret', 'access_token'],
  },
```

**Comment by azakordonets** [comment]
Since obfuscation was working only on JSON objects, the `client_secret` was not obfuscated because it was passed in form-data as a string. In `0.2.11` version I have added obfuscation for form-data format as well and that should fix your problem. Give it a try and let me know if it does not work.

**Comment by xenoterracide** [comment]
hmm... not to comment, but more to why I have 2 tickets. for things (that I'm not currently working with), like xml, it would still be good to have a way of creating a custom function to do it. I don't think you need to support more than axios supports out of the box ;)
