### ISSUE TITLE
include url in error

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#33]
would it be possible to include the request url in error logging? we have a bunch of async requests happening at once, and one of them is erroring, but hard to tell which one

**Comment by azakordonets** [comment]
Can you please share an example of the error output ? From the code it looks like we do log the error of both request and response

**Comment by xenoterracide** [comment]
some year when I have one again... but I'm referring to the output from the `errorLogger`

**Comment by azakordonets** [comment]
Will try to reproduce it :)
