### ISSUE TITLE
query params logging is not url encoding

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#34]
So query params logging is working now, but the uri string doesn't appear to be urlencoded, meaning spaces and other special characters are not escaped. You can see the space `Bearer 5w4`. Pretty minor issue though.

```ts
[back-end] ┌────── Request ──────────────────────────────────────────────────────────────────────────────────────────────
[back-end]   URL: https://company.com//as/introspect.oauth2?token=Bearer 5w4
[back-end]   Method: @POST
````

**Comment by azakordonets** [comment]
Fixed in `-0.2.13`. Thanks for letting me know all this issues :)
